### ISSUE TITLE
rendering failed for custom icons in pdf/print view

### ISSUE THREAD

**Issue by vkosuri** [tommilligan/mdbook-admonish#222]
I have defined my custom icons, but those are not properly reflected when I am in pdf/print view, is there a way to resolve this issue?

here book.toml config

```toml
[preprocessor.admonish]
command = "mdbook-admonish"
assets_version = "3.0.2" # do not edit: managed by `mdbook-admonish install`
on_failure = "bail"

[preprocessor.admonish.default]
collapsible = false

[[preprocessor.admonish.custom]]
directive = "history"
icon = "./icons/history.svg"
color = "#ff9800"

```

![image](https://github.com/user-attachments/assets/80410fc7-7eb0-46f1-913c-460b546710cf)
