### ISSUE TITLE
are there the tabs feature!

### ISSUE THREAD

**Issue by ayoubelmhamdi** [tommilligan/mdbook-admonish#29]
### UPDATE

the best feature for me in [mkdocs-material](https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#grouping-code-blocks) is the way that uses the `tabs` to groups codes

- is it supported by [mdbook-admonish](https://github.com/tommilligan/mdbook-admonish) ?
- if not, is there any way to use this feature?

![image](https://user-images.githubusercontent.com/34358145/192877022-abc2a2f0-be70-42a9-858f-47ebf4e96fa9.png)

**Comment by tommilligan** [comment]
I think you're asking about the tabs feature in `mkdocs-material`, and whether it is supported here?

The short answer is, not yet. This project doesn't aim to implement all of `mkdocs-material`; just admonishments, which are orthogonal to tabs.

However, I think you could implement a similar preprocessor step to support the tabs syntax if you wanted to. If you are interested in submitting a PR, I can take a look.

**Comment by ayoubelmhamdi** [comment]
unfortunately, I can't build this `preprocessor` now, by myself, perhaps I need to learn how `mkdocs-material` make it by `python`, then reimplement it in `rust`, but my backend at now is `c`, and `java`, and `dart`

**Comment by ayoubelmhamdi** [comment]
@tommilligan : I found a `PR` that supported `tabs`, using only a file for `css` and a file for `js`.
```toml
[output.html]
additional-css = ["./theme/tabbed-code-blocks.css"]
additional-js = ["./theme/tabbed-code-blocks.js"]
```

<details>
<summary>tabbed-code-blocks.css</summary>

```css
/* Implement tabbed code blocks for mdBook. */

.tabbed-blocks ul.tab-bar {
    padding: 0;
    margin: 0;
}

.tabbed-blocks ul.tab-bar li {
    display: inline-block;
    min-width: 4em;
    padding: 0.5em; 1em;
    text-align: center;
    user-select: none;
}

/* Use the background and border colours from mdbook-admonish info blocks. */
.tabbed-blocks ul.tab-bar li.active {
    background-color: rgba(0, 184, 212, 0.1);
    border-top: 4px solid #00b8d4;
}

.tabbed-blocks ul.tab-bar li {
    border-top: 4px solid rgba(127, 127, 127, 0.5);
}

/* Remove vertical space between tabs and code blocks. */
.tabbed-blocks pre {
    margin-top: 0;
}

```
</details>

<details>
<summary>tabbed-code-blocks.js</summary>

```js
/* Implement tabbed code blocks for mdBook. */

(function() {
"use strict";

// The CSS selector used to identify groups of tabbed code blocks.
const blocks_selector = "div.tabbed-blocks";

// The CSS class used to identify the active tab.
const class_active = "active";

// NOTE: the order in which we define the names is important, because we
// iterate over the names in the *insertion order*.
const tab_names = new Map();
tab_names.set("language-python", "Python");
tab_names.set("language-py", "Python");
tab_names.set("language-R", "R");
tab_names.set("language-cpp", "C++");
tab_names.set("language-sh", "Shell");
tab_names.set("language-shell", "Shell");
tab_names.set("language-md", "Markdown");
tab_names.set("language-text", "Text");
tab_names.set("language-diff", "Diff");

// The tab name to use when none of the above names apply.
const default_tab_name = "Unknown";

function addTabsToGroup(group) {
    // Create the container for the tab buttons.
    const tab_bar = document.createElement("ul");
    tab_bar.className = "tab-bar";
    group.prepend(tab_bar);

    // Add a tab for each code block, and hide all but the first block.
    const pre_elements = group.querySelectorAll("pre");
    pre_elements.forEach((pre_elt, ix) => {
        const tab_elt = addTabForCodeBlock(tab_bar, pre_elements, pre_elt);
        if (ix > 0) {
            pre_elt.style.display = "none";
        } else {
            tab_elt.classList.add(class_active);
        }
    });
}

function addTabForCodeBlock(tab_bar, pre_elts, pre_elt) {
    // Find the code element, from which we can identify the language.
    const code_elt = pre_elt.querySelector("code");
    // Identify the code block language.
    const tab_text = document.createTextNode(getTabTextForCode(code_elt));

    // Create the button for this tab.
    const tab_elt = document.createElement("li");
    tab_elt.appendChild(tab_text);
    tab_bar.appendChild(tab_elt);

    // Add an event handler for switching between tabs.
    addTabEventHandler(tab_elt, tab_bar, pre_elts, pre_elt);

    return tab_elt;
}

function getTabTextForCode(code_elt) {
    // Identify the language based on the code element's class.
    for (const [class_name, tab_text] of tab_names) {
        if (code_elt.classList.contains(class_name)) {
            return tab_text;
        }
    }
    return default_tab_name;
}

function addTabEventHandler(tab_elt, tab_bar, pre_elts, pre_elt) {
    tab_elt.addEventListener("click", () => {
        // Hide all code blocks.
        pre_elts.forEach((pre_elt) => {
            pre_elt.style.display = "none";
        });
        // Show this code block.
        pre_elt.style.display = "block";

        // Mark this button as the active tab.
        tab_bar.querySelectorAll("li").forEach((elt) => {
            elt.classList.remove(class_active);
        });
        tab_elt.classList.add(class_active);
    });
}

// Create a tab bar for each group of code blocks.
window.addEventListener("DOMContentLoaded", (event) => {
    const tab_groups = document.querySelectorAll(blocks_selector);
    tab_groups.forEach(addTabsToGroup);
});

})();
```
</details>
