### ISSUE TITLE
Not working on including files?

### ISSUE THREAD

**Issue by eitsupi** [tommilligan/mdbook-admonish#78]
Thank you for developing this easy-to-use extension.

In PRQL/prql#2366, I noticed that the admonish code block is not rendered as intended in the externally imported md file. (like below)
Perhaps this is a current limitation?

```md
{{#include ../../../CHANGELOG.md}}
```

**Comment by tommilligan** [comment]
Thanks for the report. After some investigation, it turns out that you can run preprocessors in a certain order: https://rust-lang.github.io/mdBook/format/configuration/preprocessors.html#require-a-certain-order

So you should be able to make this work by adding `after = ["links"]` like here
```toml
[preprocessor.admonish]
command = "mdbook-admonish"
assets_version = "2.0.0" # do not edit: managed by `mdbook-admonish install`
after = ["links"]
```
I'll add this to the readme + integration tests, as I think it's really useful to support.
